apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiqx-app
  namespace: aiqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiqx-app
  template:
    metadata:
      labels:
        app: aiqx-app
    spec:
      containers:
      - name: aiqx-app
        image: aiqx-g05:local
        resources:
          requests:
            memory: "128Mi"
            cpu: "128m"
          limits:
            memory: "128Mi"
        ports:
        - containerPort: 80
