global:
  scrape_interval: 15s # start scraping every 15 seconds

scrape_configs:
  - job_name: 'aiqx_app'
    static_configs:
      - targets: ['localhost:9100']  # metrics endpoint

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100'] 
